server:
  port: 8080

spring:
  application:
    name: prompt-management-studio-spring
  
  # OpenAI Configuration
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your_openai_api_key_here}
      chat:
        options:
          model: gpt-4
          temperature: 0.1
          max-tokens: 1000
    
    # Anthropic Configuration
    anthropic:
      api-key: ${ANTHROPIC_API_KEY:your_anthropic_api_key_here}
      chat:
        options:
          model: claude-3-sonnet-20240229
          max-tokens: 1000
    
    # Google Vertex AI Configuration
    vertex:
      ai:
        gemini:
          project-id: ${GOOGLE_PROJECT_ID:your_google_project_id_here}
          location: ${GOOGLE_LOCATION:us-central1}
          chat:
            options:
              model: gemini-pro
              temperature: 0.1
              max-output-tokens: 1000

logging:
  level:
    com.example.promptstudio: DEBUG
    org.springframework.ai: INFO 